# ghost_add_module(): one engine module = one folder with a CMakeLists.txt = one static library.
# ghost_check_module_includes(): fails the configure step when a file includes a module its module doesn't depend on.

set(GHOST_ENGINE_DIR "${CMAKE_SOURCE_DIR}/Engine")
set_property(GLOBAL PROPERTY GHOST_MODULES "")

# Graphics/Vulkan -> Ghost_Graphics_Vulkan
function(ghost_module_target out path)
  string(REPLACE "/" "_" name "Ghost_${path}")
  set(${out} "${name}" PARENT_SCOPE)
endfunction()

# Lists a module folder's .cpp/.h files, skipping nested folders that are modules of their own.
function(ghost_collect_sources out dir)
  file(GLOB_RECURSE files CONFIGURE_DEPENDS "${dir}/*.cpp" "${dir}/*.h")
  file(GLOB_RECURSE nested_lists "${dir}/*/CMakeLists.txt")
  foreach(list_file IN LISTS nested_lists)
    get_filename_component(nested_dir "${list_file}" DIRECTORY)
    set(kept "")
    foreach(f IN LISTS files)
      string(FIND "${f}" "${nested_dir}/" position)
      if(NOT position EQUAL 0)
        list(APPEND kept "${f}")
      endif()
    endforeach()
    set(files "${kept}")
  endforeach()
  set(${out} "${files}" PARENT_SCOPE)
endfunction()

# ghost_add_module(<Path under Engine/>
#                  [DEPENDS <engine modules>...]      engine modules this one may include (public)
#                  [PUBLIC_LIBS <targets>...]         third-party targets exposed in this module's headers
#                  [PRIVATE_LIBS <targets>...]        third-party targets used only in .cpp files
#                  [EXCLUDE <file names>...]          files in the folder that belong to another target
#                  [OPTIMIZE_IN_DEBUG])               build optimized even in Debug (hot CPU loops, e.g. asset import)
function(ghost_add_module path)
  cmake_parse_arguments(ARG "OPTIMIZE_IN_DEBUG" "" "DEPENDS;PUBLIC_LIBS;PRIVATE_LIBS;EXCLUDE" ${ARGN})
  ghost_module_target(target "${path}")
  ghost_collect_sources(sources "${GHOST_ENGINE_DIR}/${path}")

  set(filtered "")
  foreach(f IN LISTS sources)
    get_filename_component(name "${f}" NAME)
    if(NOT name IN_LIST ARG_EXCLUDE)
      list(APPEND filtered "${f}")
    endif()
  endforeach()

  add_library(${target} STATIC ${filtered})
  target_include_directories(${target} PUBLIC "${GHOST_ENGINE_DIR}")
  target_compile_options(${target} PRIVATE /W4 /WX)
  if(ARG_OPTIMIZE_IN_DEBUG)
    target_compile_options(${target} PRIVATE "${GHOST_OPTIMIZED_DEBUG_FLAGS}")
  else()
    target_compile_options(${target} PRIVATE "${GHOST_DEBUG_FLAGS}")
  endif()
  foreach(dep IN LISTS ARG_DEPENDS)
    ghost_module_target(dep_target "${dep}")
    target_link_libraries(${target} PUBLIC ${dep_target})
  endforeach()
  if(ARG_PUBLIC_LIBS)
    target_link_libraries(${target} PUBLIC ${ARG_PUBLIC_LIBS})
  endif()
  if(ARG_PRIVATE_LIBS)
    target_link_libraries(${target} PRIVATE ${ARG_PRIVATE_LIBS})
  endif()

  set_property(GLOBAL APPEND PROPERTY GHOST_MODULES "${path}")
  set_property(GLOBAL PROPERTY "GHOST_DEPENDS_${target}" "${ARG_DEPENDS}")
  set_property(GLOBAL PROPERTY "GHOST_SOURCES_${target}" "${sources}")
endfunction()

# The modules <path> may include: itself plus all of its dependencies, transitively.
function(ghost_allowed_modules out path)
  set(result "${path}")
  set(queue "${path}")
  while(queue)
    list(POP_FRONT queue current)
    ghost_module_target(t "${current}")
    get_property(deps GLOBAL PROPERTY "GHOST_DEPENDS_${t}")
    foreach(d IN LISTS deps)
      if(NOT d IN_LIST result)
        list(APPEND result "${d}")
        list(APPEND queue "${d}")
      endif()
    endforeach()
  endwhile()
  set(${out} "${result}" PARENT_SCOPE)
endfunction()

# Maps an include path ("Graphics/Vulkan/Device.h") to the module that owns it (longest prefix), or "".
function(ghost_module_of_include out include_path modules)
  set(best "")
  set(best_length 0)
  foreach(m IN LISTS modules)
    string(LENGTH "${m}/" length)
    string(SUBSTRING "${include_path}" 0 ${length} prefix)
    if(prefix STREQUAL "${m}/" AND length GREATER best_length)
      set(best "${m}")
      set(best_length ${length})
    endif()
  endforeach()
  set(${out} "${best}" PARENT_SCOPE)
endfunction()

# Checks every quoted #include in <files>: the owning module must be in <allowed>, and another
# module's Internal/ headers are off limits. <label> names the code being checked in error messages.
function(ghost_check_includes label self allowed files)
  get_property(modules GLOBAL PROPERTY GHOST_MODULES)
  foreach(file IN LISTS files)
    file(STRINGS "${file}" lines REGEX "^[ \t]*#[ \t]*include[ \t]*\"")
    foreach(line IN LISTS lines)
      if(NOT line MATCHES "\"([^\"]+)\"")
        continue()
      endif()
      set(include_path "${CMAKE_MATCH_1}")
      ghost_module_of_include(owner "${include_path}" "${modules}")
      if(NOT owner)
        continue()
      endif()
      file(RELATIVE_PATH rel "${CMAKE_SOURCE_DIR}" "${file}")
      if(NOT owner IN_LIST allowed)
        message(FATAL_ERROR
          "${rel} includes \"${include_path}\", but ${label} does not depend on module ${owner}.\n"
          "Add it to DEPENDS in the module's CMakeLists.txt if that direction is allowed "
          "(see Design_Vault/14 Project Structure.md).")
      endif()
      if(include_path MATCHES "/Internal/" AND NOT owner STREQUAL "${self}")
        message(FATAL_ERROR "${rel} includes \"${include_path}\": Internal/ headers are private to module ${owner}.")
      endif()
    endforeach()
  endforeach()
endfunction()

# Call once after all modules are added.
function(ghost_check_module_includes)
  get_property(modules GLOBAL PROPERTY GHOST_MODULES)
  foreach(path IN LISTS modules)
    ghost_module_target(target "${path}")
    get_property(deps GLOBAL PROPERTY "GHOST_DEPENDS_${target}")
    foreach(d IN LISTS deps)
      if(NOT d IN_LIST modules)
        message(FATAL_ERROR "Module ${path} depends on unknown module '${d}'.")
      endif()
    endforeach()
    ghost_allowed_modules(allowed "${path}")
    get_property(sources GLOBAL PROPERTY "GHOST_SOURCES_${target}")
    ghost_check_includes("module ${path}" "${path}" "${allowed}" "${sources}")
  endforeach()
endfunction()
